name: Unit Tests and Coverage

on: [push, pull_request, workflow_dispatch]

jobs:

  call-docker-login:
    uses: ./.github/workflows/docker-login.yml
    secrets:
      ROB_REMOTE_USER: ${{ secrets.ROB_REMOTE_USER }}
      ROB_REMOTE_TOKEN: ${{ secrets.ROB_REMOTE_TOKEN }}

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag robot_image

      - name: Run unit tests and coverage in Docker container
        run: |
          docker run --name coverage_container robot_image sh -c "cd /app && \
          PYTHONPATH=/app \
          xvfb-run --auto-servernum --server-num=99 \
          python -m coverage run --branch --source=/app --rcfile=.coveragerc \
          -m unittest discover -v -s BusTransactions/UnitTests -p 'test_*.py' && \
          coverage html -d coverage_html"

      - name: Copy HTML coverage report
        run: docker cp coverage_container:/app/coverage_html ./coverage_html

      - name: Report coverage in GitHub summary
        run: |
          docker cp coverage_container:/app/.coverage .coverage
          coverage report > coverage.txt
          tail -n 10 coverage.txt
          echo '### Test Coverage Summary' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

#      - name: Upload HTML coverage report
#        uses: actions/upload-artifact@v4
#        with:
#          name: coverage-html
#          path: ./coverage_html