name: Run Tests and Generate Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ROB_REMOTE_USER }}
          password: ${{ secrets.ROB_REMOTE_TOKEN }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag robot_image

      - name: Run tests with coverage inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            robot_image \
            sh -c "xvfb-run --auto-servernum --server-num=99 coverage run -m unittest discover -v && coverage xml"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          fail_ci_if_error: true
